---
- name: add users to servers and sudoers as admins
  hosts: servers
  become: true
  vars:
    groupname: wheel
    usernames:
      - user1
      - user2

  tasks:
    - name: add users
      user:
        name: "{{ item }}"
        state: present
        groups: "{{ groupname }}"
      loop: "{{ usernames }}"

    - name: Set authorized keys from a users from file
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', 'ssh-keys/{{item}}.pub') }}"
      loop: "{{ usernames }}"

    - name: list created user
      command:
        cmd: id -a "{{ item }}"
      with_items: "{{ usernames }}"
      register: result
      ignore_errors: yes
      changed_when: false

    - debug:
        msg: "{{ item['stdout'] }}"
      loop: '{{ result.results }}'
